package com.hbu.backend;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpSession;

@Slf4j
@Controller // This means that this class is a Controller
@RequestMapping(path="/demo")
public class DemoUserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DemoUserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        DemoUser n = new DemoUser();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        log.info("saved");
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<DemoUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/home")
    public String toHomeView(Model model){
        model.addAttribute("testingText", "HBU Starter installed successfully");
        return "home";
    }
}
